### ISSUE TITLE
main files

### ISSUE THREAD

**Issue by sarthakkalia** [Surya-sourav/VirtuEye#1]

**Comment by Nikkhil0646** [comment]
class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> with WifiScannerMixin<MyApp> {
 @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Text("Connected to '$connectedSSID'"),
        )       
      )   
    );
  }

  @override
  void initState() {
    super.initState();
    startWifiScanner();
  }
}

**Comment by Nikkhil0646** [comment]
Done
